// demo-app/_vue-components/user-item.vue
<template>
  <div
    v-if="user"
    class="user"
    :class="{ selected: selected }"
  >
    <span>Id: {{ user.id }}</span> - <span>{{ user.name }}</span>
    <button v-if="!unselectable" @click="$emit('selectMe', user)" :disabled="selected">
      {{ btnText }}
    </button>
  </div>
</template>

<script>
export default {
  name: 'user-item',
  emits: [
    'selectMe',
  ],
  props: {
    unselectable: Boolean,
    selected: Boolean,
    user: {
      type: Object,
      required: true,
    },
    btnText: {
      type: String,
      default: 'select',
    },
  },
};
</script>

<style scoped>
</style>

// _components/react/UserItem.js
import * as React from 'react';
import PropTypes from 'prop-types';


export default class UserItem extends React.Component {
  render() {
    const {
      selected,
      user,
      onSelectMe,
      unselectable,
      children,
    } = this.props;
    console.debug(this.props);

    return user ? (
      <div className={selected ? 'user selected' : 'user'}>
        <span>Id: {user.id}</span> -{' '}
        <span>{user.name}</span>{' '}
        {unselectable ? null :
        <button onClick={() => onSelectMe(user)} disabled={user.selected}>
          {children || 'select'}
        </button>
        }
      </div>
    ) : null;
  }

  static propTypes = {
    user: PropTypes.object,
    selected: PropTypes.bool,
    unselectable: PropTypes.bool,
    onSelectMe: PropTypes.func,
  };
}
