// components/react/UserItem.js
import * as React from "react";

export default class UserItem extends React.Component {
  handleClick = () => {
    this.props.onSelect(this.props.user);
  }

  render() {
    const className = this.props.selected ? "user selected" : "user";
    return this.props.user ? (
      <div className={className}>
        <span>Id: {this.props.user.id}</span> -{" "}
        <span>{this.props.user.name}</span>
        <button onClick={this.handleClick} disabled={this.props.selected}>
          select
        </button>
      </div>
    ) : null;
  }
}

// demo-app/_vue-components/user-item.vue
<template>
  <div
    v-if="user"
    class="user"
    :class="{ selected: selected }"
  >
    <span>Id: {{ user.id }}</span> - <span>{{ user.name }}</span>
    <button v-if="!unselectable" @click="$emit('selectMe', user)" :disabled="selected">
      {{ btnText }}
    </button>
  </div>
</template>

<script>
export default {
  name: 'user-item',
  emits: [
    'selectMe',
  ],
  props: {
    unselectable: Boolean,
    selected: Boolean,
    user: {
      type: Object,
      required: true,
    },
    btnText: {
      type: String,
      default: 'select',
    },
  },
};
</script>

<style scoped>
</style>
